ARG VERSION=bullseye-slim
From debian:latest


RUN apt update
RUN apt -y install openjdk-17-jdk 

COPY . .

RUN apt -y install maven 
RUN mvn clean install

EXPOSE 8080

COPY --from:build /target/To-do-List-1.0.0.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
